Improve isAssociation() in vm.primitives.js
codefrau/SqueakJS pull request #125
Opened 2021-03-30 05:22 UTC by ccrraaiigg

We have a Global in the special objects array, so we can be rather more specific in isAssociation(). This bit me when marshaling a complex object for use with the JS bridge.

2021-03-30 18:30 UTC, codefrau requested changes
Yes, good idea to be more specific, but in older images 
```
(Smalltalk specialObjectsArray at: 4) class === Association
```
so maybe we need to check that the superclass chain includes `LookupKey` ?

2021-03-31 01:49 UTC, codefrau commented
Alternatively, we could iterate through the array and make sure every entry is a 2-pointer object and the first of these 2 is a bytes object (ByteSymbol / ByteString).

2021-03-31 21:56 UTC, ccrraaiigg commented
Hm, I still would have been bitten. Perhaps we could check both the old and new special objects array cases, and answer true if either of them is a match?

2021-03-31 23:48 UTC, codefrau commented
Okay. We could try to find (and maybe cache) `LookupKey class` by following the superclass chain from the `Processor` global to the class that has only 1 instance variable:

```
(Smalltalk specialObjectsArray at: 4) class withAllSuperclasses collect: [:c | c -> c instSize] 

Global->2 Binding->1 LookupKey->1 Magnitude->0 Object->0 ProtoObject->0

Association->2 LookupKey->1 Magnitude->0 Object->0 

```
So maybe something like
1. `LookupKey` = starting at schedAssoc.sqClass, go up superclass chain until we find a class satisfying `cls.pointers[0].classInstSize() === 0`
2. Object in question is an `Association` if it inherits from `LookupKey` and has 2 inst vars.

2025-01-07 06:47 UTC, codefrau commented
Merged (9b315dfd108f79dd5d34a53d887641b7afb2a5db) and fixed as outlined above (e502466cec01e93e16de8eb7f02515adf63bbd74)

2025-01-07 06:47 UTC, closed without merging